# postgresql.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: sameersbn/postgresql:14-20230628
        envFrom:
        - configMapRef:
            name: gitlab-config
        - secretRef:
            name: gitlab-secrets
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql
        ports:
        - containerPort: 5432
      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: postgresql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
  - port: 5432
  selector:
    app: postgresql
